### ISSUE TITLE
AOE Loot and Mail broken 

### ISSUE THREAD

**Issue by pwestyLC** [TrinityCore/TrinityCoreCustomChanges#79] opened 2022-06-11 07:56 UTC
**Description:**
world server crashing

zul'furak in tanaris the dirt graves crash world server
creating DK, looting first weapon causes world server to crash
**Current behaviour:**
working but broken on somethings?

CHANGEME Tell us what happens.
its a world server crash but i dont have access

**Expected behaviour:**
to not crash the world server?

CHANGEME Tell us what should happen instead.
i should be able to loot the items
**Steps to reproduce the problem:**

1. make a dk or goto dugeon in tenaris "correct spelling?"
2. loot the graves = crash
3. make dk do first quest loot sword = crash

**Comment by acidmanifesto** [comment] 2022-06-14 14:27
@pwestyLC thanks for the issue report. I'm the creator of the AOE MASS Loot module. I am going to evaulation the issue now and see what remedies I can come up with once I verify the issues. Do you have a .gps you can provide for one of the graves?

**Comment by acidmanifesto** [comment] 2022-06-14 14:55
ok. so far this is what my findings are with the latest compile [c593a55](https://github.com/TrinityCore/TrinityCoreCustomChanges/commit/c593a553c5deda78f38479bd9bc9b750d14c83c2):

##**Issues Mentioned:**##
1. make a dk or goto dugeon in tenaris "correct spelling?"
See 2. and 3. below

2. loot the graves = crash UNFOUNDED
the [Shallow Grave](https://www.wowhead.com/object=128308/shallow-grave) in Zul' Farrak i do not get a crash. warriors are spawning from it as intended.
![image](https://user-images.githubusercontent.com/16887899/173608607-0a646327-e09c-4239-bcf6-e966fbc3c73e.png)

3. make dk do first quest loot sword = crash UNFOUNDED
for quest [The Emblazoned Runeblade](https://www.wowhead.com/quest=12619/the-emblazoned-runeblade) is unfounded. 
Looting the [Battle Worn Sword](https://www.wowhead.com/object=190584/battle-worn-sword)
I do not get a crash at all. i was able to complete the quest and turn in all in one try with no issues.
![image](https://user-images.githubusercontent.com/16887899/173608232-55a6a9db-ef95-4481-b0db-d3b074e05555.png)

##**Conclusion:**##
The issues CAN NOT be replicated.
At this point we will need to know what revision you are using and any other modules you are using in combination with the AOE Loot module to ensure we do not have a conflict or any other issues due to a not up to date core. If you made any custom edits to the module then we need to know what changes your made that may cause this issue to arise.
This module uses a custom grid search of a certain radius for dead creatures only and does NOT search gameobjects as the issue report claims.

**Comment by Aokromes** [comment] 2022-06-14 15:03
i suggest you to supply a crashlog.

**Comment by pwestyLC** [comment] 2022-06-15 02:24
im using the Eluna trinity 3.3.5a and im sure i was using the newest version of aoe loot system. maybe i implemented it slight wrong? but it was working just not on those 2 things. i recently erased it and went back to normal. i will redo this in the source and try again. unless The eluna trinity is the issue. doubtful. if you want crash logs let me know i'll be glad to send them

i do have a glitchy script/mod called "grumbos vip system" it messes with something on characters when using maybe this could be the issue?


also with this eluna / trinity pack.. i was forced to add
#include "Config.h"
in player.cpp because of 
### if (sConfigMgr->GetBoolDefault("AOE.LOOT.enable", true))

sConfigMgh being undefined.

**Comment by acidmanifesto** [comment] 2022-06-15 11:07
> im using the Eluna trinity 3.3.5a and im sure i was using the newest version of aoe loot system. maybe i implemented it slight wrong? but it was working just not on those 2 things. i recently erased it and went back to normal. i will redo this in the source and try again. unless The eluna trinity is the issue. doubtful. if you want crash logs let me know i'll be glad to send them
> 
> i do have a glitchy script/mod called "grumbos vip system" it messes with something on characters when using maybe this could be the issue?
> 
> 
> also with this eluna / trinity pack.. i was forced to add
> #include "Config.h"
> in player.cpp because of 
> ### if (sConfigMgr->GetBoolDefault("AOE.LOOT.enable", true))
> 
> sConfigMgh being undefined.

The include directive is present in the player.cpp already.

https://github.com/TrinityCore/TrinityCoreCustomChanges/blob/3.3.5-aoe-loot-mail-excess/src/server/game/Entities/Player/Player.cpp#L51

Do send the crash logs.

**Comment by pwestyLC** [comment] 2022-06-15 11:12
weird config wasn't in mine :/ ill get crash logs later today work or sleep is calling cant figure out which one yet lol.

i also redid the aoe thing to make sure i didnt screw up anything ill test that as well and get current crash logs. im hoping i put something in the wrong spot.

**Comment by pwestyLC** [comment] 2022-06-15 18:50
seems i put one of the corrections in the wrong spot. the issue isn't there anymore. but you might wanna add the correction in some older eluna/trinity config.h include was truly missing in player.cpp

appreciate you taking the time to test this for me, you accept donations at all for your work?

**Comment by acidmanifesto** [comment] 2022-06-15 20:19
> seems i put one of the corrections in the wrong spot. the issue isn't there anymore. but you might wanna add the correction in some older eluna/trinity config.h include was truly missing in player.cpp
> 
> appreciate you taking the time to test this for me, you accept donations at all for your work?

no donations are needed. this is what the open source community does. we help and contribute the best we can.
if the issue is no longer a issue please close it. That way we dont have to play message tag with select maintainers to close a issue. If you have anymore issues feel free to open them and i will do my best to my abilities to check up and respond since i did a few modules on the trinity core custom changes git.

**Closed as completed** 2022-06-16 01:06 UTC
